[project]
name = "simple-data-pipeline"
version = "0.1.0"
description = "Simple example to query a R2 parquet file with SQL using DuckDB or Datafusion"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datafusion>=43.1.0",
    "duckdb>=1.1.3",
    "requests>=2.32.3",
]
